config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "baking_categories#index"

  resources :baking_categories, only: [:show, :create, :new, :edit, :update, :destroy]
  post "/recipes/search", to: "recipes#search"
  get "/recipes/search", to: "recipes#results", as: "recipes_results"
  resources :recipes, only: [:create, :new, :show, :edit, :update]

  resources :directions, only: [:new]
  post "/directions/new", to: "directions#create"
  resources :ingredients, only: [:new]
  post "/ingredients/new", to: "ingredients#create"
  resources :reviews, only: [:create, :new, :destroy]

  resources :users, only: [:new, :create, :show]
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
end

app/views/includes/_direction_inputs.html.erb
<p>
  <p>
    <label>Step</label>
    <input type="text" name="directions[][step]"/>
  </p>
  <p>
    <label>Instruction</label>
    <input type="text" name="directions[][instruction]"/>
  </p>
</p>

app/views/includes/_flash_notices.html.erb
<% if flash %>
  <% flash.each do |k,v| %>
    <div class="ui transition message <%= k.to_s %>">
      <i class="close icon"></i>
      <div class="header">
        <%= k.to_s.capitalize %>
      </div>
      <p><%= v %></p>
    </div>
  <%end%>
  <% flash.clear %>
<%end%>

app/views/includes/_footer.html.erb
<div class="ui inverted vertical footer segment">
  <div class="ui center aligned container">
    <div class="ui stackable inverted divided grid">
      <div class="three wide column">
        <h4 class="ui inverted header">Baking Categories</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Cakes</a>
          <a href="#" class="item">Pies</a>
          <a href="/#baking-categories" class="item">Find More</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">About</h4>
        <div class="ui inverted link list">
          <a href="/users/new" class="item">Sign Up</a>
          <a href="/login" class="item">Log In</a>
          <a href="/logout" class="item">Log Out</a>
        </div>
      </div>
      <div class="seven wide column">
        <h4 class="ui inverted header">The Minimalist Baker</h4>
        <p>Sign up today to join our fantastic community of bakers and pastry chefs to swap recipes and tips!</p>
      </div>
    </div>
    <div class="ui inverted section divider"></div>
    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="#">Site Map</a>
      <a class="item" href="#">Contact Us</a>
      <a class="item" href="#">Terms and Conditions</a>
      <a class="item" href="#">Privacy Policy</a>
    </div>
  </div>
</div>

app/views/includes/_ingredient_inputs.html.erb
<p>
  <p>
    <label>Qty</label>
    <input type="text" name="ingredients[][qty]" />
    <select name="ingredients[][unit]", class="ui selection dropdown" >
      <% @units.each do |u| %>
        <option value="<%= u %>"><%= u %></option>
      <% end %>
    </select>
  </p>
  <p>
    <label>Item</label>
    <input type="text" name="ingredients[][name]" />
  </p>
</p>

app/views/includes/_navigation.html.erb
<div class="ui inverted segment">
  <div class="ui inverted secondary pointing menu">
    <%= link_to "Home", root_path, class: "active item" %>
    <%= link_to "Baking Categories", "/#baking-categories", class: "item" %>
    <div class="right menu">
      <% if @current_user.present? %>
        <div class="ui item">
          Welcome back, <%= @current_user.name %>!
        </div>
        <%= link_to "Your profile page", user_path(@current_user.id), class: "ui item" %>
        <%= link_to "Log out", logout_path, method: :delete, class: "ui item" %>
      <% else %>
        <%= link_to "Sign up", new_user_path, class: "ui item" %>
        <%= link_to "Log in", login_path, class: "ui item" %>
      <% end %>
    </div>
  </div>
</div>