config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "baking_categories#index"

  resources :baking_categories, only: [:show, :create, :new, :edit, :update, :destroy]
  post "/recipes/search", to: "recipes#search"
  get "/recipes/search", to: "recipes#results", as: "recipes_results"
  resources :recipes, only: [:create, :new, :show, :edit, :update]

  resources :directions, only: [:new]
  post "/directions/new", to: "directions#create"
  resources :ingredients, only: [:new]
  post "/ingredients/new", to: "ingredients#create"
  resources :reviews, only: [:create, :new, :destroy]

  resources :users, only: [:new, :create, :show]
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :baking_category
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :food_items, through: :ingredients
  has_many :reviews
  has_many :directions, dependent: :destroy
  # validates_uniqueness_of :name, scope: :baking_category_id

  def avg_rating(id)

    recipe = Recipe.find(id)
    total_rating = 0

    if !recipe.reviews.empty?
      recipe.reviews.each do |review|
        total_rating += review.rating
      end
      (total_rating / recipe.reviews.count).round(2)
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]

  def new
    @recipe = Recipe.new
    @baking_categories = BakingCategory.all
  end

  def create
    @baking_categories = BakingCategory.all
    @recipe = Recipe.new(clean_params)

    # to upload image to Cloudinary
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @recipe.image = req["public_id"]
    end

    if @recipe.save
      redirect_to new_ingredient_path(recipe_id: @recipe.id)
    else
      render :new
    end
  end

  def search
    redirect_to recipes_results_path(search: "#{params[:find]}")
  end

  # create search function with the new of "where" and "like"
  def results
    # @search_result = Recipe.where("name like ?", "%#{params[:search]}%")

    @search_result = Recipe.joins(:food_items).joins(:directions).where("food_items.name ILIKE ? OR recipes.name ILIKE ? OR directions.instruction ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").distinct
    
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    # redirect_to root_path unless @recipe.user_id = @current_user.id
    @baking_categories = BakingCategory.all
    @recipe = Recipe.find(params[:id])

    if @recipe.user_id != @current_user.id
      # this line redirects the user away from the page unless the recipe belongs to them:
      redirect_to root_path
    end

  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.user_id != @current_user.id
      # this line redirects the user away from the page unless the recipe belongs to them:
      redirect_to root_path
    end

    @recipe.update_attributes(clean_params)

# to update image in Cloudinary
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @recipe.image = req["public_id"]
      @recipe.save
    end

    redirect_to recipe_path(@recipe.id)

  end

  def destroy
    @recipe = Recipe.find(params[:id])
  end

  private

  def clean_params
    params.require(:recipe).permit(:name, :image, :skill_level, :prep_time, :cooking_time, :baking_category_id, :user_id)
  end
end

app/views/recipes/edit.html.erb
<div class="ui main text container">
  <h2>Edit this recipe</h2>
  <%= form_for(@recipe, :html => {:multipart => true, :class => "ui large form"}) do |el| %>
    <!-- <input type="hidden" name="recipe[user_id]" value="<%= @current_user.id %>" /> -->
    <p>
      <%= el.label "Baking Category" %>
        <select name="recipe[baking_category_id]", class="ui selection dropdown">
          <% @baking_categories.each do |b| %>
            <option value="<%= b.id %>"><%= b.name %></option>
          <% end %>
        </select>
    </p>
    <p>
      <%= el.label :name %>
      <%= el.text_field :name %>
    </p>
    <p>
      <%= el.label :image %>
      <%= el.cl_image_upload :image %>
    </p>
    <p>
      <%= el.label :skill_level %>
      <%= el.text_field :skill_level, placeholder: "Rate from 1 to 5" %>
    </p>
    <p>
      <%= el.label :prep_time %>
      <%= el.text_field :prep_time, placeholder: "Enter in minutes"%>
    </p>
    <p>
      <%= el.label :cooking_time %>
      <%= el.text_field :cooking_time, placeholder: "Enter in minutes" %>
    </p>
    <%= el.submit "Save", class: "ui teal basic button"%>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="ui main text container">
  <h2>Add a Recipe</h2>
  <%= form_for(@recipe, :html => {:multipart => true, :class => "ui large form"}) do |el| %>
    <input type="hidden" name="recipe[user_id]" value="<%= @current_user.id %>" />
      <p>
        <%= el.label "Baking Category" %>
          <select name="recipe[baking_category_id]", class="ui selection dropdown">
            <% @baking_categories.each do |b| %>
              <option value="<%= b.id %>"><%= b.name %></option>
            <% end %>
          </select>
      </p>
      <p>
        <%= el.label :name %>
        <%= el.text_field :name %>
      </p>
      <p>
        <%= el.label :image %>
        <%= el.cl_image_upload :image %>
      </p>
      <p>
        <%= el.label :skill_level %>
        <%= el.text_field :skill_level, placeholder: "Rate from 1 to 5" %>
      </p>
      <p>
        <%= el.label :prep_time %>
        <%= el.text_field :prep_time, placeholder: "Enter in minutes"%>
      </p>
      <p>
        <%= el.label :cooking_time %>
        <%= el.text_field :cooking_time, placeholder: "Enter in minutes" %>
      </p>
      <%= el.submit "Next", class: "ui teal basic button"%>
  <% end %>
</div>

app/views/recipes/results.html.erb
<div class="spotlight-container">
  <%= image_tag "anzac-biscuits.jpg", class: "spotlight-image" %>
</div>
<div class="ui main text container">
  <h2>Your search results</h2>
  <ul>
    <% @search_result.each do |recipe| %>
      <li><%= link_to recipe.name, recipe_path(recipe.id) %></li>
    <% end %>
  </ul>
</div>

app/views/recipes/show.html.erb
<div class="spotlight-container">
  <%= cl_image_tag @recipe.image, class: "spotlight-image" %>
  <div class="spotlight-text">
    <h1><%= @recipe.name.titleize %></h1>
      <h3>By <%= @recipe.user.name %> | Rating <%= @recipe.avg_rating @recipe.id %> (<%= @recipe.reviews.count %> reviews)</h3>
  </div>
</div>

<div class="ui text container">
  <%= render "includes/flash_notices" %>
</div>

<div class="ui main text container">
  <ul>
    <li>Difficulty: <%= @recipe.skill_level %></li>
    <li>Prep Time: <%= @recipe.prep_time %> min</li>
    <li>Cooking Time: <%= @recipe.cooking_time %> min</li>
  </ul>

<% if @current_user %>
  <% if @current_user.id == @recipe.user_id %>
    <%= link_to "Edit the recipe", edit_recipe_path, class: "ui teal basic button" %>
  <% end %>
<%end %>

  <h3>Ingredients</h3>
  <ul>
    <% @recipe.ingredients.each do |ingredient| %>
      <li><%= ingredient.qty %> <%= ingredient.unit %> <%= ingredient.food_item.name.downcase %></li>
    <% end %>

    <a href="#" id="imperial_conversion">Convert to Imperial</a> |
    <!-- create a hidden conversion div with conversions completed already -->
    <div id="hidden_imperial_conversion" style="display: none;">
      <!-- loop thru the ingredients data, and call the 'convert_formatted' method in the ingredients model to convert the ingredients then print out each item -->
      <% @recipe.ingredients.each do |ingredient| %>
        <li> <%= ingredient.convert_formatted 'Imperial' %> <%= ingredient.food_item.name.downcase %></li>
      <% end %>
    </div>
    <a href="#" id="metric_conversion">Convert to Metric</a>
    <div id="hidden_metric_conversion" style="display: none;">
      <% @recipe.ingredients.each do |ingredient| %>
        <li> <%= ingredient.convert_formatted 'Metric' %> <%= ingredient.food_item.name.downcase %></li>
      <% end %>
    </div>
  </ul>
  <h3>Directions</h3>
  <ol>
    <% @recipe.directions.each do |direction| %>
      <li><%= direction.instruction %></li>
    <% end %>
  </ol>
</div>
<div class="ui inverted segment" id="review-container">
  <div class="ui text container">
    <h3>Comments and Ratings</h3>
    <% if @recipe.reviews.empty? %>
      <p>No comments yet - be the first to rate this recipe!</p>
    <% else %>
      <% @recipe.reviews.each do |review| %>
        <div class="content" id="review">
          <p><%= review.message %></p>
          <p>Rating: <%= review.rating %> | By: <%= review.user.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<% if @current_user %>
  <div class="ui main text container">
    <% if @current_user.id != @recipe.user_id %>
      <p>What's Your Rating?</p>
      <%= form_tag reviews_path, method: :post, class: "ui large form" do %>
        <input type ="hidden" name="review[recipe_id]" value="<%= params[:id] %>" />
        <input type="hidden" name="review[user_id]" value="<%= @current_user.id %>" />
        <p>
          <input type="text" name="review[rating]" placeholder="Rating out of 5" />
        </p>
        <p>
          <label>Your Review</label>
          <input type="text" name="review[message]" placeholder="Write your review" />
        </p>
        <p>
          <input type="submit" value="Post" class="ui teal basic button" />
        </p>
      <% end %>
    <% end %>
  </div>
<% end %>
<!-- JS for clicking of conversion links to show the hidden divs -->
<script>
  $(document).ready(function(){
    $("#imperial_conversion").on("click", function(){
      $("#hidden_imperial_conversion").show();
    });
    $("#metric_conversion").on("click", function(){
      $("#hidden_metric_conversion").show();
    });
  });
</script>