config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "baking_categories#index"

  resources :baking_categories, only: [:show, :create, :new, :edit, :update, :destroy]
  post "/recipes/search", to: "recipes#search"
  get "/recipes/search", to: "recipes#results", as: "recipes_results"
  resources :recipes, only: [:create, :new, :show, :edit, :update]

  resources :directions, only: [:new]
  post "/directions/new", to: "directions#create"
  resources :ingredients, only: [:new]
  post "/ingredients/new", to: "ingredients#create"
  resources :reviews, only: [:create, :new, :destroy]

  resources :users, only: [:new, :create, :show]
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :food_item

  # create table for metric <--> imperial conversions
  @@conversion_table = {
    'Imperial' => {
      'L' => {
        'fl oz' => 35,
      },
      'ml' => {
        'fl oz' => 1/30.0,
      },
      'g' => {
        'oz' => 0.035,
      },
      'kg' => {
        'oz' => 35,
      }
    },
    'Metric' => {
      'fl oz' => {
        'L' => 1/35.0,
        'ml' => 30
      },
      'oz' => {
        'g' => 28.35,
        'kg' => 0.028
      },
      'lb' => {
        'g' => 453.59,
        'kg' => 0.45
      }
    }
  }

  def convert_formatted(measurement_sys)

    if @@conversion_table[measurement_sys].key?(unit) # check if the requested measurement system has the corresponding keys matched with the recipe ingredient units
      conversion_unit = @@conversion_table[measurement_sys][unit]
      (qty * conversion_unit.values.pop).round(2).to_s + " " + conversion_unit.keys.pop # pop the value out of the array
    else # if not in the table then return the original value
      qty.to_s + " " + unit
    end
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user, only: [:create]

  UNITS_CONST = ["ml", "L", "g", "kg", "cup", "tsp", "Tbsp", "oz", "fl oz", "lb", ""]  # array of ingredient units

  def self.unit_select
    @units = UNITS_CONST.sort
  end

  def new
    @ingredient = Ingredient.new
    @units = UNITS_CONST.sort
  end

  def create
    params[:ingredients].each do |i|
      if i[:qty].present? && i[:name].present? # check that both fields are not empty
        food_item = FoodItem.find_or_create_by(name: i[:name])
        @recipe = Recipe.find(params[:recipe_id]) # need both food item and recipe references create new ingredients
        @ingredients = Ingredient.create(qty: i[:qty], unit: i[:unit], food_item_id: food_item.id, recipe_id: @recipe.id)
      end
    end
    if @ingredients.save
      redirect_to new_direction_path(recipe_id: @recipe.id)
    else
      render :new
    end
  end

  def edit
    # @ingredients = Ingredient.find_by(recipe_id: params[:id])
    # @units = UNITS_CONST.sort
    # food_item = FoodItem.find(id: i.food_item_id).name
  end

  def update
  end

  private

  def clean_params
    params.require(:ingredients).permit(:qty, :food_item_id, :recipe_id, :unit)
  end
end

app/views/ingredients/edit.html.erb
<div class="ui main text container">
  <h2>Edit the ingredients</h2>
  <%= form_for @ingredients, html: {class: "ui large form"} do |i| %>
    <p>
      <%= i.label :qty %>
      <%= i.text_field :qty %>
    </p>
    <select name="ingredients[][unit]", class="ui selection dropdown">
      <% @units.each do |u| %>
        <option value="<%= u %>"><%= u %></option>
      <% end %>
    </select>
    <p>
      <%= i.label :item %>
      <%= i.text_field :food_item[name] %>
    </p>
  <% end %>
</div>

app/views/ingredients/new.html.erb
<div class="ui main text container">
  <h2>What goes in it? Add the ingredients</h2>
  <%= form_tag new_ingredient_path, method: "post", class: "ui form" do %>
    <input type="hidden" name="recipe_id" value="<%= params[:recipe_id] %>" />
    <div id="ingredient_inputs">
      <%= render "/includes/ingredient_inputs" %>
    </div>
    <p>
      <input type="submit" value="Next" class="ui teal basic button"/>
  </p>
  <% end %>
  <a href="#" id="add_ingredient">More +</a>
  <div id="hidden_inputs" style="display: none;">
    <%= render "/includes/ingredient_inputs" %>
  </div>
  <script>
    $(document).ready(function(){
      $("#add_ingredient").on("click", function(e){
        e.preventDefault();
        var inputs = $("#hidden_inputs").html();
        $("#ingredient_inputs").append(inputs);
      })
    });
  </script>
</div>