config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "baking_categories#index"

  resources :baking_categories, only: [:show, :create, :new, :edit, :update, :destroy]
  post "/recipes/search", to: "recipes#search"
  get "/recipes/search", to: "recipes#results", as: "recipes_results"
  resources :recipes, only: [:create, :new, :show, :edit, :update]

  resources :directions, only: [:new]
  post "/directions/new", to: "directions#create"
  resources :ingredients, only: [:new]
  post "/ingredients/new", to: "ingredients#create"
  resources :reviews, only: [:create, :new, :destroy]

  resources :users, only: [:new, :create, :show]
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
end

app/models/baking_category.rb
class BakingCategory < ApplicationRecord
  has_many :recipes
  validates_uniqueness_of :name
end

app/controllers/baking_categories_controller.rb
class BakingCategoriesController < ApplicationController
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]

  def index
    @baking_categories = BakingCategory.all.order(:name) # Baking categories sort alphabetically using "order by name"
  end

  def new
    @baking_category = BakingCategory.new
  end

  def create
    @baking_category = BakingCategory.create(clean_params)
    redirect_to root_path
  end

  def edit
    @baking_category = BakingCategory.find(params[:id])
  end

  def update
    @baking_category = BakingCategory.find(params[:id])
    @baking_category.update_attributes(clean_params)
    redirect_to root_path
  end

  def show
    @baking_category = BakingCategory.find(params[:id])
  end

  def destroy
    if @current_user.admin
      baking_category = BakingCategory.find(params[:id]).destroy
      flash[:success] = "You deleted #{baking_category.name}"
      redirect_to root_path
    else
      flash[:error] = "Access denied"
      redirect_to root_path
    end
  end

  private

  def clean_params
    params.require(:baking_category).permit(:name, :image)
  end

end

app/views/baking_categories/edit.html.erb
<div class="ui main text container">
  <h2>Edit this baking category</h2>
  <%= form_for @baking_category, html: {class: "ui large form"} do |b| %>
    <p>
      <%= b.label :name %>
      <%= b.text_field :name %>
    </p>
      <%= b.submit "Save", class: "ui teal basic button" %>
  <% end %>
</div>

app/views/baking_categories/index.html.erb
<div class="spotlight-container">
  <%= image_tag "header_img.jpg", class: "spotlight-image" %>
  <div class="spotlight-text">
    <h1>The Minimalist Baker</h1>
    <h2>Simpler baking - with less fuss</h2>
    <%= link_to "See Our Recipes", "/#baking-categories", class: "ui inverted teal basic button" %>
  </div>
</div>
<div class="ui inverted segment" id="feature-container">
  <div class="ui text container">
    <h2>1,000 amazing baking recipes for you to try!</h2>
      <%= form_tag recipes_search_path, method: "post", class: "ui large form" do %>
        <p>
          <%= text_field_tag :find, nil, placeholder: "Enter search term...", id: "search-field" %>
          <%= submit_tag "Search", class: "ui teal basic button", id: "search-button" %>
        </p>
        <div class="content">
          <ul>
            <li><%= link_to @baking_categories.first.name, baking_category_path(@baking_categories.first.id) %></li>
            <li><%= link_to @baking_categories.second.name, baking_category_path(@baking_categories.second.id) %></li>
            <li><%= link_to @baking_categories.last.name, baking_category_path(@baking_categories.last.id) %></li>
          </ul>
        </div>
      <% end %>
  </div>
</div>
<div class="ui text container">
  <a name="baking-categories"><h1>Baking Categories</h1></a>
</div>
<div class="ui grid">
  <% @baking_categories.each do |b| %>
    <div class="four wide column">
      <h3><%= b.name %></h3>
      <%= link_to image_tag(b.image, class: "category-img"), baking_category_path(b.id) %>
        <% if @current_user && @current_user.admin %>
          <br><%= link_to "Edit", edit_baking_category_path(b.id), class: "ui teal basic button" %> <%= link_to "Delete", baking_category_path(b.id), class: "ui teal basic button", method: :delete, data: {confirm: "Are you sure you want to delete the #{b.name} category?"} %></br>
        <% end %>
    </div>
  <% end %>
</div>
<div class="ui inverted segment" id="feature-container">
  <div class="ui text container">
    <% if @current_user && @current_user.admin %>
      <h2>Welcome back, <%= @current_user.name %>!</h2>
        <%= link_to "Add a New Baking Category", new_baking_category_path, class: "ui teal basic button" %>
    <% end %>
    <% if @current_user %>
      <h2>Share your delicious recipe today</h2>
      <%= link_to "Add a New Recipe", new_recipe_path, class: "ui teal basic button" %>
    <% end %>
    <% if !@current_user %>
      <h2>Join The Minimalist Baker Today!</h2>
      <%= link_to "Sign Up Now", new_user_path, class: "ui teal basic button" %>
    <% end %>
  </div>
</div>

app/views/baking_categories/new.html.erb
<div class="ui main text container">
  <h2>Add a New Baking Category</h2>
  <%= form_for @baking_category, html: {class: "ui large form"} do |b| %>
    <p>
      <%= b.label :name %>
      <%= b.text_field :name %>
    </p>
    <%= b.submit "Submit", class: "ui teal basic button" %>
  <% end %>
</div>

app/views/baking_categories/show.html.erb
<!-- <div class="spotlight-container">
  <%= image_tag "black-forest-cake.jpg", class: "spotlight-image" %>
  <div class="spotlight-text">
    <h2><%= @baking_category.name %></h2>
  </div>
</div> -->
<div class="ui main text container">
  <h2><%= @baking_category.name %></h2>
  <ul>
    <% @baking_category.recipes.order(:name).each do |recipe| %>
      <li><%= link_to recipe.name, recipe_path(recipe.id) %></li>
    <% end %>
  </ul>
</div>